### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhengguanyu** [Acruxos/GLAME#1]
非常感谢您的工作。我在运行时遇到了一个问题，请问是否缺失文件？

报错位置-> `GLAME/experiment/glame/__init__.py`

`from .egat_net import build_graph_from_triples`

报错信息->

ModuleNotFoundError: No module named 'glame.egat_net'

**Comment by Acruxos** [comment]
感谢您的关注！

这里整理代码的时候遗漏了个小bug，build_graph_from_triples在GLAME/experiment/glame/build_graph.py中，现已更正

**Comment by zhengguanyu** [comment]
好的，感谢您的回复

**Comment by zhengguanyu** [comment]
另外，还有一个报错想请教您。

报错位置->`experiment/glame/compute_v.py  , line 196, in compute_v`

`target_delta_feature = delta+subject_feature`

NameError: name 'delta' is not defined

**Comment by Acruxos** [comment]
修正了一下 `compute_v.py` ，刚刚测试了下，现在应该可以正常运行

**Comment by zhengguanyu** [comment]
感谢修复，可以运行
